export const fonts = {
  'PlayfairDisplay-Regular': require('@/assets/fonts/PlayfairDisplay-Regular.ttf'),
  'PlayfairDisplay-Medium': require('@/assets/fonts/PlayfairDisplay-Medium.ttf'),
  'PlayfairDisplay-SemiBold': require('@/assets/fonts/PlayfairDisplay-SemiBold.ttf'),
  'PlayfairDisplay-Bold': require('@/assets/fonts/PlayfairDisplay-Bold.ttf'),
  'PlayfairDisplay-ExtraBold': require('@/assets/fonts/PlayfairDisplay-ExtraBold.ttf'),
  'PlayfairDisplay-Black': require('@/assets/fonts/PlayfairDisplay-Black.ttf'),
  'Poppins-Thin': require('@/assets/fonts/Poppins-Thin.ttf'),
  'Poppins-ExtraLight': require('@/assets/fonts/Poppins-ExtraLight.ttf'),
  'Poppins-Light': require('@/assets/fonts/Poppins-Light.ttf'),
  'Poppins-Regular': require('@/assets/fonts/Poppins-Regular.ttf'),
  'Poppins-Medium': require('@/assets/fonts/Poppins-Medium.ttf'),
  'Poppins-SemiBold': require('@/assets/fonts/Poppins-SemiBold.ttf'),
  'Poppins-Bold': require('@/assets/fonts/Poppins-Bold.ttf'),
  'Poppins-ExtraBold': require('@/assets/fonts/Poppins-ExtraBold.ttf'),
  'Poppins-Black': require('@/assets/fonts/Poppins-Black.ttf'),
};
